import os
import uuid
import json
import time
import math
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit Log ─────────────────────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ── Signal 1: LLM Classification (Groq) ───────────────────────────────────

def llm_signal(text):
    prompt = f"""You are evaluating whether a piece of text was written by a human or generated by AI.

Analyze the following text and return ONLY a single decimal number between 0.0 and 1.0:
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was AI-generated
- Values in between reflect your uncertainty

Consider: uniformity of sentence structure, presence of personal voice, natural imperfections, 
overuse of transition phrases, and unnatural fluency.

Text to analyze:
{text}

Respond with ONLY the number. Nothing else."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=10,
    )
    raw = response.choices[0].message.content.strip()
    try:
        score = float(raw)
        return max(0.0, min(1.0, score))
    except ValueError:
        return 0.5


# ── Signal 2: Stylometric Heuristics ──────────────────────────────────────

def stylometric_signal(text):
    import re

    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = text.split()
    
    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # too short to score reliably

    # Sentence length variance (lower variance = more AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Normalize: std_dev of ~8+ is human-like, ~2 or less is AI-like
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # Type-token ratio (lower TTR = more repetitive = more AI-like)
    unique_words = set(w.lower().strip(".,!?;:\"'") for w in words)
    ttr = len(unique_words) / len(words)
    # Normalize: TTR of 0.8+ is human-like, 0.4 or less is AI-like
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.4) / 0.4)))

    # Punctuation density (AI text tends to have moderate, consistent punctuation)
    punct_count = sum(1 for c in text if c in ",.!?;:—–")
    punct_density = punct_count / len(words)
    # Very low or very high density is more human-like
    punct_score = max(0.0, min(1.0, 1.0 - abs(punct_density - 0.15) / 0.15))

    stylo_score = (variance_score * 0.5) + (ttr_score * 0.3) + (punct_score * 0.2)
    return round(stylo_score, 3)


# ── Confidence Scoring ─────────────────────────────────────────────────────

def combine_signals(llm_score, stylo_score):
    return round((0.6 * llm_score) + (0.4 * stylo_score), 3)


# ── Transparency Label ─────────────────────────────────────────────────────

def generate_label(confidence):
    pct = round(confidence * 100)
    if confidence >= 0.65:
        return {
            "verdict": "likely_ai",
            "text": (
                f"⚠️ AI-Generated Content\n"
                f"Our system found strong indicators that this content was AI-generated.\n"
                f"Confidence: {pct}%\n"
                f"This label is based on automated analysis and may not be perfect. "
                f"The creator can submit an appeal if this is incorrect."
            )
        }
    elif confidence >= 0.36:
        return {
            "verdict": "uncertain",
            "text": (
                f"🔍 Attribution Uncertain\n"
                f"Our system could not confidently determine whether this content was written "
                f"by a human or generated by AI.\n"
                f"Confidence: {pct}%\n"
                f"Treat this content with that uncertainty in mind. "
                f"The creator can submit an appeal to provide additional context."
            )
        }
    else:
        return {
            "verdict": "likely_human",
            "text": (
                f"✅ Likely Human-Written\n"
                f"Our system found strong indicators that this content was written by a human.\n"
                f"Confidence: {pct}%\n"
                f"This label is based on automated analysis and may not be perfect."
            )
        }


# ── Routes ─────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = combine_signals(llm_score, stylo_score)
    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": label["verdict"],
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": label["verdict"],
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": label["text"],
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    entries = read_log()
    updated = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            updated = True
            break

    if not updated:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)
    return jsonify({
        "message": "Appeal received. Your submission is now under review.",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})


if __name__ == "__main__":
    app.run(debug=True, port=5001)